### ISSUE TITLE
Move the repo to labs/tools in Gerrit

### ISSUE THREAD

**Issue by srish** [tonythomas01/gdrive-to-commons#12]
@tonythomas01 If we are considering to do some more work on this app, and make it available for users and contributors, it would be nice to host it in Gerrit under labs/tools, etc.

**Comment by nicolas-raoul** [comment]
_Note: Some Wikimedia-related projects live a happy life on GitHub, an advantage being that many more people are familiar with GitHub than with Gerrit, and an inconvenient [or two](https://en.wikipedia.org/wiki/GitHub#Acquisition_by_Microsoft) being that GitHub's platform is proprietary._

**Comment by srish** [comment]
@nicolas-raoul That is a good point :) I didn't consider that. 

@tonythomas01 Maybe then this could live under Wikimedia repo on Github once it is in a ready to use state?

**Comment by tonythomas01** [comment]
This is exactly what I was thinking. Lets move to Gerrit once things are usable. Sometimes, it might be easier to get contributors via Github. 

We need to have a development guide ready.

**Comment by tonythomas01** [comment]
Some first steps are happening here. I requested for a repo at https://www.mediawiki.org/w/index.php?title=Gerrit/New_repositories/Requests/Entries&action=history

**Comment by tonythomas01** [comment]
This was done :) Thanks to paladox and qchris.
