### ISSUE TITLE
Build a functional stats counter for uploads

### ISSUE THREAD

**Issue by tonythomas01** [tonythomas01/gdrive-to-commons#17]
We are storing information about the number of files uploaded by the app. it would be a nice thingy to show a counter or something like that on the home page ? 
1. Track the counts at the backend in a table. 
2. Show them up on the homepage.

**Comment by abbasidaniyal** [comment]
I am working on it!

**Comment by tonythomas01** [comment]
Great PR, but I think we should not just store the numbers. Sorry for not linking this before, but the task got modified https://phabricator.wikimedia.org/T241464 and as you can see, the idea is to store the whole upload information and later to get the stats, do a SUM of `number_of_files` on the number of objects in there.

**Comment by abbasidaniyal** [comment]
Alright. I'll start working on it! Should push an update soon

**Comment by tonythomas01** [comment]
I see we have i now. Closing.
