### ISSUE TITLE
Update setup documentations 

### ISSUE THREAD

**Issue by tonythomas01** [tonythomas01/gdrive-to-commons#3]
Missing: 
1. Development environment setup information. 
2. Deployment setup information.

**Comment by srish** [comment]
Maybe could introduce environment variables, if we haven't added them yet for a smooth deployment process. 

Also, consider leaving comments like in:
https://github.com/wikimedia/mediawiki-api-demos/blob/master/apps/picture-of-the-day-viewer/app.py#L116
https://github.com/wikimedia/mediawiki-api-demos/blob/master/apps/nearby-places-viewer/templates/places.html#L3

**Comment by NdibeRaymond** [comment]
Hello, I am an outreachy intern and I would love to take on this issue @srish
