### ISSUE TITLE
Not able to select multiple images

### ISSUE THREAD

**Issue by RishikaBhatia17** [tonythomas01/gdrive-to-commons#34]
On Windows 10, Ubuntu 18.04, mac OS (Desktop Web Browsers)
The user is not able to select multiple images from google drive according to their wish. The only way to select multiple files is using the selection tool with cursor but in this way the user can select only consecutive images and they can't select random images.
![image (1) (1)](https://user-images.githubusercontent.com/46782283/76366690-b7c69600-6350-11ea-9896-cc0939943b97.png)
On Android 10 (Mobile browser)
The user is not able to select multiple images from google drive according to their wish. They can't even select consecutive multiple files because there is no selection tool available in mobiles. Hence, the user can upload only one photo at a time.
![Screenshot_20200311-041106](https://user-images.githubusercontent.com/46782283/76366705-c319c180-6350-11ea-96be-81d668a705d5.jpg)
Users who want to upload 2 or more than 2 pictures may not like the way of uploading only one picture at a time and most probably won't like to repeat the whole process for uploading all the pictures.

See: https://phabricator.wikimedia.org/T247367

**Comment by tonythomas01** [comment]
Connected phab link :https://phabricator.wikimedia.org/T247367

**Comment by tonythomas01** [comment]
I think the problem would lie in the Google image picker component. Dont know if it would be an easy fix though.

**Comment by tonythomas01** [comment]
I see that we fixed this already. Thank you :) Closing it as resolved.
