### ISSUE TITLE
Button "choose photos from google drive" not working

### ISSUE THREAD

**Issue by simransinghal** [tonythomas01/gdrive-to-commons#40]
**To Reproduce**
1. Login to Wikimedia commons with meta account
2.  Select the "CHOOSE PHOTOS FROM GOOGLE DRIVE" action button

**Actual behavior**
After clicking on the "CHOOSE PHOTOS FROM GOOGLE DRIVE" button, there is no action taken, that is, it is stuck. After click on this multiple times also it is not showing any response.

**Expected behavior**
After clicking on the "CHOOSE PHOTOS FROM GOOGLE DRIVE" button, it should show us the photos from our google drive and should let us select the photos.

**Screenshots**
![gdrive-to-commons](https://user-images.githubusercontent.com/18376639/76628728-35fa8680-6563-11ea-99dd-4bfdb244084f.png)

**Desktop:**
 - OS: Ubuntu 18.04.3 LTS
 - Browser: Firefox
 - Version: 70.0.1 (64-bit)

**Comment by tonythomas01** [comment]
Can you verify if this is a problem only on Firefox ? I can see it working on chrome though. Good find, and thank you!

**Comment by simransinghal** [comment]
Yes, facing this problem only on Firefox. On chrome, I am facing issue #36 .
