### ISSUE TITLE
Post upload, show a better screen listing uploaded files

### ISSUE THREAD

**Issue by tonythomas01** [tonythomas01/gdrive-to-commons#55]
Right now, we have this one: 
![Screenshot 2020-04-04 at 11 04 08](https://user-images.githubusercontent.com/4214481/78423064-04f20b00-7664-11ea-86ad-c73b8687b4ed.png)

can we change it a bit like this: 
1. Make the second column bigger, and maybe just have 2 columns there and make the name a link which opens in a new page ? Like that, we can totally avoid the 3rd column. 
2. Lets see if we can take out a link to the file instead ? for eg, https://test.wikipedia.org/wiki/File:Tail_latency_comparison_between_DS,_OS_and_FS_at_varying_latency_sleep_bxp-1515415386.png and not the upload file iteslf ?

**Comment by abbasidaniyal** [comment]
I would like to take this up. 
1.  We can use row formatter to make custom design rather than depend on Tabulator entirely.
2. The response from the wikimedia API does return the URL of the file page.
