### ISSUE TITLE
style: Lets make "Date of Creation (first published)" column header a bit nicer ?

### ISSUE THREAD

**Issue by tonythomas01** [tonythomas01/gdrive-to-commons#64]
This one looks a bit weird now. How will we make it fit with the date input column width ? 
 
![Screenshot 2020-04-25 at 18 27 36](https://user-images.githubusercontent.com/4214481/80285028-73d1f980-8722-11ea-98ae-7a3775dafb6d.png)

**Comment by RishikaBhatia17** [comment]
Hi @tonythomas01 
I have created a PR to solve this issue. I request you to review it and merge it 
Thanks!

**Comment by tonythomas01** [comment]
Thank you. Closing it as resolved for now.
