### ISSUE TITLE
Fix file thumbnails on the review screen

### ISSUE THREAD

**Issue by srish** [tonythomas01/gdrive-to-commons#7]
Currently, for all file thumbnails, we are using `iconUrl` returned in the Google API callback for all files. But, this is not the actual file thumbnail and URL to a default icon which is the same for all files.

**Comment by NdibeRaymond** [comment]
I would love to work on this @srish . Can you provide more details?

**Comment by tonythomas01** [comment]
I can see that we are not doing this anymore :) Closing it for now.
