### ISSUE TITLE
Separate javascript code from HTML file

### ISSUE THREAD

**Issue by srish** [tonythomas01/gdrive-to-commons#9]
Well, it was a Hackathon, but this file is really messed up https://github.com/tonythomas01/gdrive_to_commons/blob/master/uploader/templates/base/base.html ;-) 

All the javascript code needs to be moved out in a separate file.

**Comment by tonythomas01** [comment]
Sure. I just brought back things to `home.html` without even looking at this issue. Great we have it reported. 

Now probably someone should split the things in `home.html` (scripts, etc).

**Comment by NdibeRaymond** [comment]
Hello @srish , I am an outreachy aspirant and I would love to work on this issue

**Comment by tonythomas01** [comment]
Closing this for now, as it should come more as a refactoring challenge.
